version: '3'

# Based on https://www.twilio.com/blog/get-started-docker-symfony

services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
    ports:
      - '4306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql

  php-fpm:
    build:
      context: php-fpm
    ports:
      - '9000:9000'
    environment:
      SSH_AUTH_SOCK: /keyring
    volumes:
      - ../:/var/www/my_symfony_project
      - "${SSH_AUTH_SOCK}:/keyring"
    depends_on:
      - database

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ../:/var/www/my_symfony_project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../var/log/nginx:/var/log/nginx
    depends_on:
      - php-fpm
      - database
